import {
  discountPercent,
  savingsCents,
  type Category,
  type OfferDetail,
  type OfferImage,
  type OfferSource,
  type Sport,
  type Store,
} from '@fitcupons/shared';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();
const hoursFromNow = (h: number) => new Date(now + h * 3_600_000).toISOString();
const daysFromNow = (d: number) => new Date(now + d * 86_400_000).toISOString();

export const mockSports: Sport[] = [
  { id: 'spt_cyc', slug: 'cycling', name: 'Ciclismo', iconName: 'bike', sortOrder: 1, active: true },
  { id: 'spt_run', slug: 'running', name: 'Corrida', iconName: 'run', sortOrder: 2, active: true },
  { id: 'spt_swm', slug: 'swimming', name: 'Natação', iconName: 'swim', sortOrder: 3, active: true },
  { id: 'spt_bt', slug: 'beach-tennis', name: 'Beach Tennis', iconName: 'tennis', sortOrder: 4, active: true },
  { id: 'spt_vol', slug: 'volleyball', name: 'Vôlei', iconName: 'volleyball', sortOrder: 5, active: true },
  { id: 'spt_tri', slug: 'triathlon', name: 'Triathlon', iconName: 'triathlon', sortOrder: 6, active: true },
  { id: 'spt_gym', slug: 'gym', name: 'Musculação', iconName: 'dumbbell', sortOrder: 7, active: true },
  { id: 'spt_cf', slug: 'crossfit', name: 'CrossFit', iconName: 'weight-lifter', sortOrder: 8, active: true },
  { id: 'spt_ftb', slug: 'football', name: 'Futebol', iconName: 'soccer', sortOrder: 9, active: true },
  { id: 'spt_bsk', slug: 'basketball', name: 'Basquete', iconName: 'basketball', sortOrder: 10, active: true },
  { id: 'spt_srf', slug: 'surfing', name: 'Surf', iconName: 'surfing', sortOrder: 11, active: true },
  { id: 'spt_trl', slug: 'trail', name: 'Trilha', iconName: 'hiking', sortOrder: 12, active: true },
  { id: 'spt_yog', slug: 'yoga', name: 'Yoga', iconName: 'yoga', sortOrder: 13, active: true },
  { id: 'spt_sup', slug: 'supplements', name: 'Suplementos', iconName: 'nutrition', sortOrder: 14, active: true },
];

export const mockCategories: Category[] = [
  { id: 'cat_foot', slug: 'footwear', name: 'Calçados', iconName: 'shoe-sneaker', color: '#5F4B8B', parentId: null, sortOrder: 1, children: [] },
  { id: 'cat_app', slug: 'apparel', name: 'Roupas', iconName: 'tshirt-crew', color: '#3E8E6B', parentId: null, sortOrder: 2, children: [] },
  { id: 'cat_sup', slug: 'supplements', name: 'Suplementos', iconName: 'bottle-tonic', color: '#8B6B4B', parentId: null, sortOrder: 3, children: [] },
  { id: 'cat_eq', slug: 'equipment', name: 'Equipamentos', iconName: 'dumbbell', color: '#4B6B8B', parentId: null, sortOrder: 4, children: [] },
  { id: 'cat_bike', slug: 'bikes', name: 'Bicicletas e peças', iconName: 'bike', color: '#6B4B8B', parentId: null, sortOrder: 5, children: [] },
  { id: 'cat_acc', slug: 'accessories', name: 'Acessórios', iconName: 'bag-personal', color: '#4B8B6B', parentId: null, sortOrder: 6, children: [] },
  { id: 'cat_wear', slug: 'wearables', name: 'Relógios e monitores', iconName: 'watch', color: '#8B4B6B', parentId: null, sortOrder: 7, children: [] },
  { id: 'cat_nut', slug: 'nutrition', name: 'Nutrição', iconName: 'food-apple', color: '#6B8B4B', parentId: null, sortOrder: 8, children: [] },
  { id: 'cat_rec', slug: 'recovery', name: 'Recuperação', iconName: 'spa', color: '#4B8B8B', parentId: null, sortOrder: 9, children: [] },
  { id: 'cat_srv', slug: 'services', name: 'Serviços e assinaturas', iconName: 'card-account-details', color: '#8B8B4B', parentId: null, sortOrder: 10, children: [] },
];

export const mockStores: Store[] = [
  { id: 'str_ml', slug: 'mercado-livre', name: 'Mercado Livre', logoUrl: 'https://picsum.photos/seed/ml/64', websiteUrl: 'https://www.mercadolivre.com.br', active: true },
  { id: 'str_amz', slug: 'amazon', name: 'Amazon', logoUrl: 'https://picsum.photos/seed/amz/64', websiteUrl: 'https://www.amazon.com.br', active: true },
  { id: 'str_ali', slug: 'aliexpress', name: 'AliExpress', logoUrl: 'https://picsum.photos/seed/ali/64', websiteUrl: 'https://www.aliexpress.com', active: true },
  { id: 'str_net', slug: 'netshoes', name: 'Netshoes', logoUrl: 'https://picsum.photos/seed/net/64', websiteUrl: 'https://www.netshoes.com.br', active: true },
  { id: 'str_cen', slug: 'centauro', name: 'Centauro', logoUrl: 'https://picsum.photos/seed/cen/64', websiteUrl: 'https://www.centauro.com.br', active: true },
  { id: 'str_dec', slug: 'decathlon', name: 'Decathlon', logoUrl: 'https://picsum.photos/seed/dec/64', websiteUrl: 'https://www.decathlon.com.br', active: true },
  { id: 'str_grw', slug: 'growth', name: 'Growth Supplements', logoUrl: 'https://picsum.photos/seed/grw/64', websiteUrl: 'https://www.gsuplementos.com.br', active: true },
  { id: 'str_tf', slug: 'track-field', name: 'Track&Field', logoUrl: 'https://picsum.photos/seed/tf/64', websiteUrl: 'https://www.tf.com.br', active: true },
];

function pics(seed: string, count: number): OfferImage[] {
  return Array.from({ length: count }, (_, i) => {
    const url = `https://picsum.photos/seed/${seed}${i}/800/800`;
    return {
      id: `${seed}_${i}`,
      urlThumb: url,
      urlCard: url,
      urlFull: url,
      width: 800,
      height: 800,
      blurhash: null,
      alt: null,
      sortOrder: i,
    };
  });
}

function sportById(id: string) {
  const sport = mockSports.find((item) => item.id === id);
  if (!sport) throw new Error(`Unknown sport ${id}`);
  return { id: sport.id, slug: sport.slug, name: sport.name, iconName: sport.iconName };
}

function storeById(id: string) {
  const store = mockStores.find((item) => item.id === id);
  if (!store) throw new Error(`Unknown store ${id}`);
  return { id: store.id, slug: store.slug, name: store.name, logoUrl: store.logoUrl };
}

function categoryById(id: string | null) {
  if (!id) return null;
  const category = mockCategories.find((item) => item.id === id);
  if (!category) return null;
  return { id: category.id, slug: category.slug, name: category.name, iconName: category.iconName };
}

type Seed = {
  id: string;
  slug: string;
  title: string;
  priceCents: number | null;
  originalPriceCents: number | null;
  couponCode: string | null;
  publishedAt: string;
  expiresAt: string | null;
  featured?: boolean;
  verified?: boolean;
  viewCount?: number;
  clickCount?: number;
  source?: OfferSource;
  destinationUrl: string;
  affiliateUrl?: string | null;
  description: string | null;
  storeId: string;
  categoryId: string | null;
  sportIds: string[];
  imageSeed: string;
  imageCount: number;
};

function offer(seed: Seed): OfferDetail {
  const price = seed.priceCents ?? 0;
  const original = seed.originalPriceCents ?? 0;
  const expiresAt = seed.expiresAt;
  return {
    id: seed.id,
    slug: seed.slug,
    title: seed.title,
    priceCents: seed.priceCents,
    originalPriceCents: seed.originalPriceCents,
    currency: 'BRL',
    discountPercent: discountPercent(original, price),
    savingsCents: savingsCents(original, price),
    couponCode: seed.couponCode,
    hasCoupon: Boolean(seed.couponCode),
    publishedAt: seed.publishedAt,
    expiresAt,
    endingSoon: Boolean(expiresAt && new Date(expiresAt).getTime() - now < 48 * 3_600_000),
    featured: seed.featured ?? false,
    verified: seed.verified ?? true,
    isFavorite: false,
    viewCount: seed.viewCount ?? 40,
    store: storeById(seed.storeId),
    category: categoryById(seed.categoryId),
    sports: seed.sportIds.map(sportById),
    images: pics(seed.imageSeed, seed.imageCount),
    description: seed.description,
    destinationUrl: seed.destinationUrl,
    affiliateUrl: seed.affiliateUrl ?? null,
    source: seed.source ?? 'manual',
    startsAt: null,
    clickCount: seed.clickCount ?? 8,
  };
}

const seeds: Seed[] = [
  {
    id: 'off_pegasus',
    slug: 'tenis-nike-pegasus-41-a3f9',
    title: 'Tênis Nike Pegasus 41 Masculino',
    priceCents: 39590,
    originalPriceCents: 59990,
    couponCode: 'FIT20',
    publishedAt: hoursAgo(2),
    expiresAt: daysFromNow(12),
    featured: true,
    viewCount: 128,
    clickCount: 34,
    destinationUrl: 'https://www.netshoes.com.br/pegasus',
    affiliateUrl: 'https://www.netshoes.com.br/pegasus?tag=fit',
    description: 'Amortecimento ReactX para treinos longos. Oferta por tempo limitado.',
    storeId: 'str_net',
    categoryId: 'cat_foot',
    sportIds: ['spt_run'],
    imageSeed: 'pegasus',
    imageCount: 3,
  },
  {
    id: 'off_whey',
    slug: 'whey-growth-900g',
    title: 'Whey Protein Concentrado 900g Growth',
    priceCents: 8990,
    originalPriceCents: 14990,
    couponCode: null,
    publishedAt: hoursAgo(8),
    expiresAt: hoursFromNow(36),
    viewCount: 410,
    clickCount: 91,
    destinationUrl: 'https://www.gsuplementos.com.br/whey',
    description: 'Whey concentrado 80% de proteína, sabor chocolate.',
    storeId: 'str_grw',
    categoryId: 'cat_sup',
    sportIds: ['spt_gym', 'spt_sup'],
    imageSeed: 'whey',
    imageCount: 2,
  },
  {
    id: 'off_bike',
    slug: 'speed-caloi-strada',
    title: 'Speed Caloi Strada 16v',
    priceCents: 289900,
    originalPriceCents: 429900,
    couponCode: 'PEDAL15',
    publishedAt: daysAgo(1),
    expiresAt: daysFromNow(20),
    featured: true,
    viewCount: 76,
    clickCount: 12,
    source: 'mercado_livre',
    destinationUrl: 'https://www.mercadolivre.com.br/caloi',
    affiliateUrl: 'https://www.mercadolivre.com.br/caloi?matt_word=ALISSON3208',
    description: 'Quadro de alumínio, 16 velocidades. Pronta entrega.',
    storeId: 'str_ml',
    categoryId: 'cat_bike',
    sportIds: ['spt_cyc'],
    imageSeed: 'bike',
    imageCount: 4,
  },
  {
    id: 'off_garmin',
    slug: 'garmin-forerunner-165',
    title: 'Garmin Forerunner 165',
    priceCents: 179900,
    originalPriceCents: 249900,
    couponCode: 'PACE10',
    publishedAt: daysAgo(4),
    expiresAt: daysFromNow(5),
    featured: true,
    viewCount: 201,
    clickCount: 55,
    source: 'amazon',
    destinationUrl: 'https://www.amazon.com.br/garmin',
    description: 'GPS, métricas avançadas e tela AMOLED.',
    storeId: 'str_amz',
    categoryId: 'cat_wear',
    sportIds: ['spt_run', 'spt_tri'],
    imageSeed: 'garmin',
    imageCount: 2,
  },
  {
    id: 'off_yoga',
    slug: 'kit-yoga-decathlon',
    title: 'Kit tapete + bloco de yoga Decathlon',
    priceCents: 7990,
    originalPriceCents: 12990,
    couponCode: null,
    publishedAt: daysAgo(2),
    expiresAt: null,
    verified: true,
    viewCount: 64,
    clickCount: 11,
    destinationUrl: 'https://www.decathlon.com.br/yoga',
    description: 'Tapete 6mm + dois blocos de EVA.',
    storeId: 'str_dec',
    categoryId: 'cat_eq',
    sportIds: ['spt_yog'],
    imageSeed: 'yoga',
    imageCount: 1,
  },
  {
    id: 'off_adizero',
    slug: 'adidas-adizero-boston-12',
    title: 'Tênis Adidas Adizero Boston 12',
    priceCents: 49990,
    originalPriceCents: 79990,
    couponCode: 'CORRIDA10',
    publishedAt: hoursAgo(5),
    expiresAt: hoursFromNow(30),
    viewCount: 88,
    destinationUrl: 'https://www.centauro.com.br/adizero',
    affiliateUrl: 'https://www.centauro.com.br/adizero?tag=fit',
    description: 'Placa de nylon e espuma Lightstrike Pro.',
    storeId: 'str_cen',
    categoryId: 'cat_foot',
    sportIds: ['spt_run'],
    imageSeed: 'adizero',
    imageCount: 3,
  },
  {
    id: 'off_shorts',
    slug: 'shorts-tf-run',
    title: 'Shorts Track&Field Run 5"',
    priceCents: 12990,
    originalPriceCents: 19990,
    couponCode: null,
    publishedAt: hoursAgo(14),
    expiresAt: daysFromNow(9),
    destinationUrl: 'https://www.tf.com.br/shorts',
    description: 'Tecido leve com bolso traseiro para gel.',
    storeId: 'str_tf',
    categoryId: 'cat_app',
    sportIds: ['spt_run', 'spt_trl'],
    imageSeed: 'shorts',
    imageCount: 2,
  },
  {
    id: 'off_helmet',
    slug: 'capacete-giro-syntax',
    title: 'Capacete Giro Syntax MIPS',
    priceCents: 45990,
    originalPriceCents: 69990,
    couponCode: 'PEDAL15',
    publishedAt: hoursAgo(20),
    expiresAt: daysFromNow(6),
    source: 'mercado_livre',
    destinationUrl: 'https://www.mercadolivre.com.br/giro',
    affiliateUrl: 'https://www.mercadolivre.com.br/giro?matt_word=ALISSON3208',
    description: 'Proteção MIPS e 25 entradas de ar.',
    storeId: 'str_ml',
    categoryId: 'cat_bike',
    sportIds: ['spt_cyc'],
    imageSeed: 'helmet',
    imageCount: 3,
  },
  {
    id: 'off_creatine',
    slug: 'creatina-growth-250g',
    title: 'Creatina Monohidratada 250g Growth',
    priceCents: 4990,
    originalPriceCents: 7990,
    couponCode: 'WHEY5',
    publishedAt: daysAgo(1.5),
    expiresAt: daysFromNow(18),
    destinationUrl: 'https://www.gsuplementos.com.br/creatina',
    description: 'Creatina pura, sem sabor.',
    storeId: 'str_grw',
    categoryId: 'cat_sup',
    sportIds: ['spt_gym', 'spt_cf'],
    imageSeed: 'creatine',
    imageCount: 1,
  },
  {
    id: 'off_goggles',
    slug: 'oculos-speedo-fastskin',
    title: 'Óculos de natação Speedo Fastskin',
    priceCents: 18990,
    originalPriceCents: 24990,
    couponCode: null,
    publishedAt: daysAgo(3),
    expiresAt: daysFromNow(14),
    destinationUrl: 'https://www.centauro.com.br/oculos',
    description: 'Vedação anatômica para treinos de velocidade.',
    storeId: 'str_cen',
    categoryId: 'cat_acc',
    sportIds: ['spt_swm', 'spt_tri'],
    imageSeed: 'goggles',
    imageCount: 2,
  },
  {
    id: 'off_racket',
    slug: 'raquete-drop-shot-explorer',
    title: 'Raquete Drop Shot Explorer Pro',
    priceCents: 68990,
    originalPriceCents: 99990,
    couponCode: 'BEACH10',
    publishedAt: hoursAgo(30),
    expiresAt: hoursFromNow(40),
    destinationUrl: 'https://www.netshoes.com.br/raquete',
    affiliateUrl: 'https://www.netshoes.com.br/raquete?tag=fit',
    description: 'Equilíbrio médio, ótima para intermediários.',
    storeId: 'str_net',
    categoryId: 'cat_eq',
    sportIds: ['spt_bt'],
    imageSeed: 'racket',
    imageCount: 3,
  },
  {
    id: 'off_ball',
    slug: 'bola-mikasa-v200w',
    title: 'Bola de vôlei Mikasa V200W',
    priceCents: 42990,
    originalPriceCents: 59990,
    couponCode: null,
    publishedAt: daysAgo(5),
    expiresAt: daysFromNow(21),
    source: 'amazon',
    destinationUrl: 'https://www.amazon.com.br/mikasa',
    description: 'Bola oficial FIVB, microfibra.',
    storeId: 'str_amz',
    categoryId: 'cat_eq',
    sportIds: ['spt_vol'],
    imageSeed: 'mikasa',
    imageCount: 2,
  },
  {
    id: 'off_wetsuit',
    slug: 'longjohn-ripcurl',
    title: 'Longjohn Rip Curl 3/2 mm',
    priceCents: 89990,
    originalPriceCents: 129900,
    couponCode: 'SURF12',
    publishedAt: daysAgo(2.2),
    expiresAt: daysFromNow(8),
    destinationUrl: 'https://www.decathlon.com.br/longjohn',
    description: 'Neoprene flexível para água fria.',
    storeId: 'str_dec',
    categoryId: 'cat_app',
    sportIds: ['spt_srf'],
    imageSeed: 'wetsuit',
    imageCount: 3,
  },
  {
    id: 'off_trail',
    slug: 'tenis-salomon-ultra-glide',
    title: 'Tênis Salomon Ultra Glide 2',
    priceCents: 54990,
    originalPriceCents: 84990,
    couponCode: null,
    publishedAt: hoursAgo(40),
    expiresAt: daysFromNow(11),
    destinationUrl: 'https://www.decathlon.com.br/salomon',
    description: 'Amortecimento macio para trail longo.',
    storeId: 'str_dec',
    categoryId: 'cat_foot',
    sportIds: ['spt_trl', 'spt_run'],
    imageSeed: 'salomon',
    imageCount: 4,
  },
  {
    id: 'off_bar',
    slug: 'barra-proteica-growth',
    title: 'Barra proteica Growth display 12un',
    priceCents: 7190,
    originalPriceCents: 10790,
    couponCode: 'WHEY5',
    publishedAt: daysAgo(6),
    expiresAt: daysFromNow(30),
    destinationUrl: 'https://www.gsuplementos.com.br/barra',
    description: '12 unidades, sabor cookies.',
    storeId: 'str_grw',
    categoryId: 'cat_nut',
    sportIds: ['spt_sup', 'spt_gym'],
    imageSeed: 'bar',
    imageCount: 1,
  },
  {
    id: 'off_foam',
    slug: 'foam-roller-decathlon',
    title: 'Rolo de massagem 45 cm Decathlon',
    priceCents: 5990,
    originalPriceCents: 9990,
    couponCode: null,
    publishedAt: daysAgo(3.5),
    expiresAt: null,
    destinationUrl: 'https://www.decathlon.com.br/foam',
    description: 'Densidade média para recuperação.',
    storeId: 'str_dec',
    categoryId: 'cat_rec',
    sportIds: ['spt_run', 'spt_cyc', 'spt_yog'],
    imageSeed: 'foam',
    imageCount: 2,
  },
  {
    id: 'off_boot',
    slug: 'chuteira-nike-mercurial',
    title: 'Chuteira Nike Mercurial Society',
    priceCents: 32990,
    originalPriceCents: 49990,
    couponCode: 'GOL15',
    publishedAt: hoursAgo(11),
    expiresAt: daysFromNow(4),
    destinationUrl: 'https://www.netshoes.com.br/mercurial',
    affiliateUrl: 'https://www.netshoes.com.br/mercurial?tag=fit',
    description: 'Cabedal Textreme, trava society.',
    storeId: 'str_net',
    categoryId: 'cat_foot',
    sportIds: ['spt_ftb'],
    imageSeed: 'mercurial',
    imageCount: 3,
  },
  {
    id: 'off_hoop',
    slug: 'tenis-jordan-luka-3',
    title: 'Tênis Jordan Luka 3',
    priceCents: 69990,
    originalPriceCents: 99990,
    couponCode: null,
    publishedAt: daysAgo(7),
    expiresAt: daysFromNow(16),
    source: 'amazon',
    destinationUrl: 'https://www.amazon.com.br/luka',
    description: 'Amortecimento Formula 23 para quadra.',
    storeId: 'str_amz',
    categoryId: 'cat_foot',
    sportIds: ['spt_bsk'],
    imageSeed: 'luka',
    imageCount: 3,
  },
  {
    id: 'off_kb',
    slug: 'kettlebell-16kg',
    title: 'Kettlebell 16 kg emborrachado',
    priceCents: 15990,
    originalPriceCents: 22990,
    couponCode: 'BOX8',
    publishedAt: daysAgo(4.5),
    expiresAt: hoursFromNow(20),
    source: 'aliexpress',
    destinationUrl: 'https://www.aliexpress.com/kettlebell',
    description: 'Base larga, pegada texturizada.',
    storeId: 'str_ali',
    categoryId: 'cat_eq',
    sportIds: ['spt_cf', 'spt_gym'],
    imageSeed: 'kb',
    imageCount: 2,
  },
  {
    id: 'off_trisuit',
    slug: 'trijump-decathlon',
    title: 'Trijump Decathlon Van Rysel',
    priceCents: 39990,
    originalPriceCents: 59990,
    couponCode: null,
    publishedAt: daysAgo(8),
    expiresAt: daysFromNow(25),
    destinationUrl: 'https://www.decathlon.com.br/trijump',
    description: 'Tecidos de rápida secagem, bolsos traseiros.',
    storeId: 'str_dec',
    categoryId: 'cat_app',
    sportIds: ['spt_tri'],
    imageSeed: 'trisuit',
    imageCount: 2,
  },
  {
    id: 'off_mat',
    slug: 'watch-amazfit-active',
    title: 'Amazfit Active GPS',
    priceCents: 49990,
    originalPriceCents: 79990,
    couponCode: 'PACE10',
    publishedAt: hoursAgo(50),
    expiresAt: daysFromNow(3),
    source: 'amazon',
    destinationUrl: 'https://www.amazon.com.br/amazfit',
    description: 'GPS integrado e 14 dias de bateria.',
    storeId: 'str_amz',
    categoryId: 'cat_wear',
    sportIds: ['spt_run', 'spt_gym'],
    imageSeed: 'amazfit',
    imageCount: 2,
  },
  {
    id: 'off_swimcap',
    slug: 'touca-silicone-speedo',
    title: 'Touca de silicone Speedo',
    priceCents: 3990,
    originalPriceCents: 6990,
    couponCode: null,
    publishedAt: daysAgo(9),
    expiresAt: null,
    destinationUrl: 'https://www.centauro.com.br/touca',
    description: 'Silicone grosso, menos rasgo no cabelo.',
    storeId: 'str_cen',
    categoryId: 'cat_acc',
    sportIds: ['spt_swm'],
    imageSeed: 'cap',
    imageCount: 1,
  },
  {
    id: 'off_strava',
    slug: 'strava-subscription',
    title: 'Assinatura Strava anual',
    priceCents: 19990,
    originalPriceCents: 29990,
    couponCode: 'STRAVA20',
    publishedAt: daysAgo(10),
    expiresAt: daysFromNow(40),
    destinationUrl: 'https://www.strava.com',
    description: 'Segmentos ao vivo e estatísticas avançadas.',
    storeId: 'str_tf',
    categoryId: 'cat_srv',
    sportIds: ['spt_run', 'spt_cyc'],
    imageSeed: 'strava',
    imageCount: 1,
  },
  {
    id: 'off_bottle',
    slug: 'garrafa-camelbak-750',
    title: 'Garrafa CamelBak Podium 750 ml',
    priceCents: 8990,
    originalPriceCents: 12990,
    couponCode: null,
    publishedAt: daysAgo(11),
    expiresAt: daysFromNow(15),
    destinationUrl: 'https://www.decathlon.com.br/camelbak',
    description: 'Bico de alta vazão, livre de BPA.',
    storeId: 'str_dec',
    categoryId: 'cat_acc',
    sportIds: ['spt_cyc', 'spt_run'],
    imageSeed: 'bottle',
    imageCount: 2,
  },
];

export const mockOffers: OfferDetail[] = seeds.map(offer);
